env:
  es2021: true
  node: true
  "browser": true

extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module


rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  no-console: 0
